# Auto-generated by gen-bazel-deps.py — do not edit manually.
# Re-generate with:
#   python3 nix/gen-bazel-deps.py \
#     --lockfile MODULE.bazel.lock \
#     --bcr $(nix-build --no-out-link -E 'with import <nixpkgs> {}; callPackage ./nix/bcr.nix {}') \
#     --module-bazel MODULE.bazel \
#     > nix/bazel-deps.nix
# 89 archives
[
  {
    url = "https://dl.grafana.com/grafana/release/12.3.1/grafana_12.3.1_20271043721_linux_amd64.tar.gz";
    sha256 = "75d03b5ac2dc7b009625869355225d73e5b29866efbd999479bdd24429a695db";
    name = "grafana_12.3.1_20271043721_linux_amd64.tar.gz";
  }
  {
    url = "https://dl.grafana.com/grafana/release/12.3.1/grafana_12.3.1_20271043721_linux_arm64.tar.gz";
    sha256 = "889cac6634a365dacbc712e1e49ea2233d40b9c958e61266f39949537ce63cdd";
    name = "grafana_12.3.1_20271043721_linux_arm64.tar.gz";
  }
  {
    url = "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2025-04-03T14-56-28Z";
    sha256 = "cebd628ae859b4670de9c04b0cbf5600a498166da2031ad634c987208d89ae94";
    name = "minio.RELEASE.2025-04-03T14-56-28Z";
  }
  {
    url = "https://dl.min.io/server/minio/release/linux-arm64/archive/minio.RELEASE.2025-04-03T14-56-28Z";
    sha256 = "5ecf7891298aebe495928f84e6eaf3b59cb7dddb499c7add8c5027eb0ba8f0e9";
    name = "minio.RELEASE.2025-04-03T14-56-28Z";
  }
  {
    url = "https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.3.tar.xz";
    sha256 = "78262a6e7ac170d6528ebfe2efccdf220191a5af6a6cd61ea4a9a9a5042c7a07";
    name = "libxml2-2.15.3.tar.xz";
  }
  {
    url = "https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl";
    sha256 = "ae74fb96c20a0277a1d615f1e4d73c8414f5a98db8b799a7931d1582f3390c28";
    name = "click-8.1.7-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/0d/dc/38f4ce065e92c66f058ea7a368a9c5de4e702272b479c0992059f7693941/pip_tools-7.4.1-py3-none-any.whl";
    sha256 = "4c690e5fbae2f21e87843e89c26191f0d9454f362d8acdbd695716493ec8b3a9";
    name = "pip_tools-7.4.1-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/25/6e/ca4a5434eb0e502210f591b97537d322546e4833dcb4d470a48c375c5540/pep517-0.13.1-py3-none-any.whl";
    sha256 = "31b206f67165b3536dd577c5c3f1518e8fbaf38cbc57efff8369a392feff1721";
    name = "pep517-0.13.1-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/2d/0a/679461c511447ffaf176567d5c496d1de27cbe34a87df6677d7171b2fbd4/importlib_metadata-7.1.0-py3-none-any.whl";
    sha256 = "30962b96c0c223483ed6cc7280e7f0199feb01a0e40cfae4d4450fc6fab1f570";
    name = "importlib_metadata-7.1.0-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/49/df/1fceb2f8900f8639e278b056416d49134fb8d84c5942ffaa01ad34782422/packaging-24.0-py3-none-any.whl";
    sha256 = "2ddfb553fdf02fb784c234c7ba6ccc288296ceabec964ad2eae3777778130bc5";
    name = "packaging-24.0-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/50/e2/8e10e465ee3987bb7c9ab69efb91d867d93959095f4807db102d07995d94/more_itertools-10.2.0-py3-none-any.whl";
    sha256 = "686b06abe565edfab151cb8fd385a05651e1fdf8f0a14191e4439283421f8684";
    name = "more_itertools-10.2.0-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl";
    sha256 = "55c570405f142630c6b9f72fe09d9b67cf1477fcf543ae5b8dcb1f5b7377da81";
    name = "wheel-0.43.0-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/8a/6a/19e9fe04fca059ccf770861c7d5721ab4c2aebc539889e97c7977528a53b/pip-24.0-py3-none-any.whl";
    sha256 = "ba0d021a166865d2265246961bec0152ff124de910c5cc39f1156ce3fa7c69dc";
    name = "pip-24.0-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/90/99/158ad0609729111163fc1f674a5a42f2605371a4cf036d0441070e2f7455/setuptools-78.1.1-py3-none-any.whl";
    sha256 = "c3a9c4211ff4c309edb8b8c4f1cbfa7ae324c4ba9f91ff254e3d305b9fd54561";
    name = "setuptools-78.1.1-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
    sha256 = "939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc";
    name = "tomli-2.0.1-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/ae/f3/431b9d5fe7d14af7a32340792ef43b8a714e7726f1d7b69cc4e8e7a3f1d7/pyproject_hooks-1.1.0-py3-none-any.whl";
    sha256 = "7ceeefe9aec63a1064c18d939bdc3adf2d8aa1988a510afec15151578b232aa2";
    name = "pyproject_hooks-1.1.0-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl";
    sha256 = "4f1d9991f5acc0ca119f9d443620b77f9d6b33703e51011c16baf57afb285fc6";
    name = "colorama-0.4.6-py2.py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/da/55/a03fd7240714916507e1fcf7ae355bd9d9ed2e6db492595f1a67f61681be/zipp-3.18.2-py3-none-any.whl";
    sha256 = "dce197b859eb796242b0622af1b8beb0a722d52aa2f57133ead08edd5bf5374e";
    name = "zipp-3.18.2-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/e2/03/f3c8ba0a6b6e30d7d18c40faab90807c9bb5e9a1e3b2fe2008af624a9c97/build-1.2.1-py3-none-any.whl";
    sha256 = "75e10f767a433d9a86e50d83f418e83efc18ede923ee5ff7df93b6cb0306c5d4";
    name = "build-1.2.1-py3-none-any.whl";
  }
  {
    url = "https://files.pythonhosted.org/packages/e5/ca/1172b6638d52f2d6caa2dd262ec4c811ba59eee96d54a7701930726bce18/installer-0.7.0-py3-none-any.whl";
    sha256 = "05d1933f0a5ba7d8d6296bb6d5018e7c94fa473ceb10cf198a92ccea19c27b53";
    name = "installer-0.7.0-py3-none-any.whl";
  }
  {
    url = "https://github.com/JetBrains/kotlin/releases/download/v1.9.23/kotlin-compiler-1.9.23.zip";
    sha256 = "93137d3aab9afa9b27cb06a824c2324195c6b6f6179d8a8653f440f5bd58be88";
    name = "kotlin-compiler-1.9.23.zip";
  }
  {
    url = "https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.11.0.tar.gz";
    sha256 = "c24379b5fa0a429a1f9a3fc23b44a75f2b141a34c09146a529a55d20a5808070";
    name = "v2.11.0.tar.gz";
  }
  {
    url = "https://github.com/NixOS/patchelf/releases/download/0.18.0/patchelf-0.18.0.tar.gz";
    sha256 = "64de10e4c6b8b8379db7e87f58030f336ea747c0515f381132e810dbf84a86e7";
    name = "patchelf-0.18.0.tar.gz";
  }
  {
    url = "https://github.com/abseil/abseil-cpp/releases/download/20250814.1/abseil-cpp-20250814.1.tar.gz";
    sha256 = "1692f77d1739bacf3f94337188b78583cf09bab7e420d2dc6c5605a4f86785a1";
    name = "abseil-cpp-20250814.1.tar.gz";
  }
  {
    url = "https://github.com/adrian-thurston/colm-suite/archive/8841e561489e948a9fc497ffec233cacf6195175.tar.gz";
    sha256 = "6b29070d9f45615c45fdc3c1ea9374b206dca5db690dcb8d33848aacdfb62454";
    name = "8841e561489e948a9fc497ffec233cacf6195175.tar.gz";
  }
  {
    url = "https://github.com/antithesishq/antithesis-sdk-cpp/archive/refs/tags/0.4.7.tar.gz";
    sha256 = "e083cec08b4e173df23e0b07beda5509eddebc1f11d9adc71a8a39d0a229da97";
    name = "0.4.7.tar.gz";
  }
  {
    url = "https://github.com/apple/swift-argument-parser/archive/refs/tags/1.3.1.tar.gz";
    sha256 = "4d964f874b251abc280ee28f0f187de3c13a6122a9561524f66a10768ca2d837";
    name = "1.3.1.tar.gz";
  }
  {
    url = "https://github.com/axboe/liburing/archive/refs/tags/liburing-2.14.tar.gz";
    sha256 = "5f80964108981c6ad979c735f0b4877d5f49914c2a062f8e88282f26bf61de0c";
    name = "liburing-2.14.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/bazel-gazelle/releases/download/v0.45.0/bazel-gazelle-v0.45.0.tar.gz";
    sha256 = "e467b801046b6598c657309b45d2426dc03513777bd1092af2c62eebf990aca5";
    name = "bazel-gazelle-v0.45.0.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/bazel_features/releases/download/v1.42.1/bazel_features-v1.42.1.tar.gz";
    sha256 = "8189bac9a6bf9cc155a854c4cbebfebf58b9ca7a2d0a67645f7d0c1f83c523ac";
    name = "bazel_features-v1.42.1.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/rules_foreign_cc/releases/download/0.15.1/rules_foreign_cc-0.15.1.tar.gz";
    sha256 = "32759728913c376ba45b0116869b71b68b1c2ebf8f2bcf7b41222bc07b773d73";
    name = "rules_foreign_cc-0.15.1.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/rules_go/releases/download/v0.59.0/rules_go-v0.59.0.zip";
    sha256 = "68af54cb97fbdee5e5e8fe8d210d15a518f9d62abfd71620c3eaff3b26a5ff86";
    name = "rules_go-v0.59.0.zip";
  }
  {
    url = "https://github.com/bazel-contrib/rules_jvm_external/releases/download/6.7/rules_jvm_external-6.7.tar.gz";
    sha256 = "a1e351607f04fed296ba33c4977d3fe2a615ed50df7896676b67aac993c53c18";
    name = "rules_jvm_external-6.7.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/rules_python/releases/download/1.7.0/rules_python-1.7.0.tar.gz";
    sha256 = "f609f341d6e9090b981b3f45324d05a819fd7a5a56434f849c761971ce2c47da";
    name = "rules_python-1.7.0.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/supply-chain/releases/download/v0.0.5/supply-chain-v0.0.5.tar.gz";
    sha256 = "49ed11e5d6b752c55fa539cbb10b2736974f347b081d7bd500a80dacb7dbec06";
    name = "supply-chain-v0.0.5.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/apple_support/releases/download/1.24.2/apple_support.1.24.2.tar.gz";
    sha256 = "8625cc7b7b2952e38101e17b4a9e7c043b3a79f55d26e4772819891998725e16";
    name = "apple_support.1.24.2.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz";
    sha256 = "6e78f0e57de26801f6f564fa7c4a48dc8b36873e416257a92bbb0937eeac8446";
    name = "bazel-skylib-1.8.2.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/platforms/releases/download/1.0.0/platforms-1.0.0.tar.gz";
    sha256 = "3384eb1c30762704fbe38e440204e114154086c8fc8a8c2e3e28441028c019a8";
    name = "platforms-1.0.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_android/archive/refs/tags/v0.1.1.tar.gz";
    sha256 = "6461c1c5744442b394f46645957d6bd3420eb1b421908fe63caa03091b1b3655";
    name = "v0.1.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip";
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806";
    name = "v0.1.1.zip";
  }
  {
    url = "https://github.com/bazelbuild/rules_apple/releases/download/4.1.0/rules_apple.4.1.0.tar.gz";
    sha256 = "20152b14d9a420afc15ace905c02fd6425ddceb084630f3f043b287adf0fcdbd";
    name = "rules_apple.4.1.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_cc/releases/download/0.2.17/rules_cc-0.2.17.tar.gz";
    sha256 = "283fa1cdaaf172337898749cf4b9b1ef5ea269da59540954e51fba0e7b8f277a";
    name = "rules_cc-0.2.17.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_java/releases/download/9.1.0/rules_java-9.1.0.tar.gz";
    sha256 = "4e1a28a25c2efa53500c928d22ceffbc505dd95b335a2d025836a293b592212f";
    name = "rules_java-9.1.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_kotlin/releases/download/v1.9.6/rules_kotlin-v1.9.6.tar.gz";
    sha256 = "3b772976fec7bdcda1d84b9d39b176589424c047eb2175bed09aac630e50af43";
    name = "rules_kotlin-v1.9.6.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_license/releases/download/1.0.0/rules_license-1.0.0.tar.gz";
    sha256 = "26d4021f6898e23b82ef953078389dd49ac2b5618ac564ade4ef87cced147b38";
    name = "rules_license-1.0.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/1.0.1/rules_pkg-1.0.1.tar.gz";
    sha256 = "d20c951960ed77cb7b341c2a59488534e494d5ad1d30c4818c736d57772a9fef";
    name = "rules_pkg-1.0.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_proto/releases/download/7.1.0/rules_proto-7.1.0.tar.gz";
    sha256 = "14a225870ab4e91869652cfd69ef2028277fc1dc4910d65d353b62d6e0ae21f4";
    name = "rules_proto-7.1.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_rust/releases/download/0.70.0/rules_rust-0.70.0.tar.gz";
    sha256 = "5ffd9ff1f6f2f14f2057b7cbaa91a5e6acd9a4cbded5ac81dad9beb36859601e";
    name = "rules_rust-0.70.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_shell/releases/download/v0.6.1/rules_shell-v0.6.1.tar.gz";
    sha256 = "e6b87c89bd0b27039e3af2c5da01147452f240f75d505f5b6880874f31036307";
    name = "rules_shell-v0.6.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_swift/releases/download/3.1.2/rules_swift.3.1.2.tar.gz";
    sha256 = "5eff717c18bb513285b499add68f2331509cd4e411ff085e96a86b3342c1e5aa";
    name = "rules_swift.3.1.2.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/stardoc/releases/download/0.7.2/stardoc-0.7.2.tar.gz";
    sha256 = "0e1ed4a98f26e718776bd64d053d02bb34d98572ccd03d6ba355112a1205706b";
    name = "stardoc-0.7.2.tar.gz";
  }
  {
    url = "https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.gz";
    sha256 = "4d27e9efed0f6f152dc28db6430b9d3dfb40c0345da7342eaa5a987dde57bd95";
    name = "boost-1.84.0.tar.gz";
  }
  {
    url = "https://github.com/bufbuild/protovalidate/releases/download/v1.2.0/protovalidate-1.2.0.tar.gz";
    sha256 = "9aee9beede94edc62fa472a58c964741f11e1a0ab7472f12cfb98381c2f502fd";
    name = "protovalidate-1.2.0.tar.gz";
  }
  {
    url = "https://github.com/bufbuild/rules_buf/archive/refs/tags/v0.3.0.tar.gz";
    sha256 = "89c6d6e6523802ee7f1210340a69fab4ee0b47554953a1ecbe359319fd3f93dc";
    name = "v0.3.0.tar.gz";
  }
  {
    url = "https://github.com/bytecodealliance/wasmtime/archive/9e1084ffac08b1bf9c82de40c0efc1baff14b9ad.tar.gz";
    sha256 = "a7f989b170d109696b928b4b3d1ec1d930064af7df47178e1341bd96e5c34465";
    name = "9e1084ffac08b1bf9c82de40c0efc1baff14b9ad.tar.gz";
  }
  {
    url = "https://github.com/danielaparker/jsoncons/archive/ffd2540bc9cfb54c16ef4d29d80622605d8dfbe8.tar.gz";
    sha256 = "078ba32cd1198cbeb1903fbf4881d4960b226bdf8083d9f5a927b96f0aa8d6dd";
    name = "ffd2540bc9cfb54c16ef4d29d80622605d8dfbe8.tar.gz";
  }
  {
    url = "https://github.com/doctest/doctest/archive/refs/tags/v2.4.12.tar.gz";
    sha256 = "73381c7aa4dee704bd935609668cf41880ea7f19fa0504a200e13b74999c2d70";
    name = "v2.4.12.tar.gz";
  }
  {
    url = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz";
    sha256 = "eb33e51f49a15e023950cd7825ca74a4a2b43db8354825ac24fc1b7ee09e6fa3";
    name = "zstd-1.5.7.tar.gz";
  }
  {
    url = "https://github.com/fmeum/buildozer/releases/download/v8.5.1/buildozer-v8.5.1.tar.gz";
    sha256 = "bd0786e0f8b6aed8c35898b4c06f64ba853d61d7c8361edb5a8d43c6ea37f5c6";
    name = "buildozer-v8.5.1.tar.gz";
  }
  {
    url = "https://github.com/fmeum/googleapis-rules-registry/releases/download/v1.0.0/googleapis-rules-registry-v1.0.0.tar.gz";
    sha256 = "af7b098716da243485a91e1e679b2c7c8ee28bb391b734ddcb1adce5a992e9be";
    name = "googleapis-rules-registry-v1.0.0.tar.gz";
  }
  {
    url = "https://github.com/fmtlib/fmt/releases/download/12.1.0/fmt-12.1.0.zip";
    sha256 = "695fd197fa5aff8fc67b5f2bbc110490a875cdf7a41686ac8512fb480fa8ada7";
    name = "fmt-12.1.0.zip";
  }
  {
    url = "https://github.com/foonathan/lexy/archive/refs/tags/v2025.05.0.tar.gz";
    sha256 = "ae867846b890b7564d633cf28d39dfc4938fe7c54515126f720c1762de5eab30";
    name = "v2025.05.0.tar.gz";
  }
  {
    url = "https://github.com/google/boringssl/releases/download/0.20250818.0/boringssl-0.20250818.0.tar.gz";
    sha256 = "64529449ef458381346b163302523a1fb876e5b667bec4a4bd38d0d2fff8b42b";
    name = "boringssl-0.20250818.0.tar.gz";
  }
  {
    url = "https://github.com/google/crc32c/archive/refs/tags/1.1.0.tar.gz";
    sha256 = "49de137bf1c2eb6268d5122674f7dd1524b9148ba65c7b85c5ae4b9be104a25a";
    name = "1.1.0.tar.gz";
  }
  {
    url = "https://github.com/google/googletest/releases/download/v1.17.0/googletest-1.17.0.tar.gz";
    sha256 = "65fab701d9829d38cb77c14acdc431d2108bfdbf8979e40eb8ae567edf10b27c";
    name = "googletest-1.17.0.tar.gz";
  }
  {
    url = "https://github.com/google/ksp/releases/download/1.9.23-1.0.20/artifacts.zip";
    sha256 = "ee0618755913ef7fd6511288a232e8fad24838b9af6ea73972a76e81053c8c2d";
    name = "artifacts.zip";
  }
  {
    url = "https://github.com/google/libprotobuf-mutator/archive/dc4ced337a9fb4047e2dc727268fbac55ca82f73.zip";
    sha256 = "0847a2ee65552a92643131e934b50164e8b79fadc7be24b180a1c8d6dbb05952";
    name = "dc4ced337a9fb4047e2dc727268fbac55ca82f73.zip";
  }
  {
    url = "https://github.com/google/re2/releases/download/2024-07-02/re2-2024-07-02.zip";
    sha256 = "a835fe55fbdcd8e80f38584ab22d0840662c67f2feb36bd679402da9641dc71e";
    name = "re2-2024-07-02.zip";
  }
  {
    url = "https://github.com/google/snappy/archive/refs/tags/1.2.2.tar.gz";
    sha256 = "90f74bc1fbf78a6c56b3c4a082a05103b3a56bb17bca1a27e052ea11723292dc";
    name = "1.2.2.tar.gz";
  }
  {
    url = "https://github.com/googleapis/googleapis/archive/f9d6fe4a6ad9ed89dfc315f284124d2104377940.zip";
    sha256 = "07283fe78fd8834604d79e5009f3c96761f94135c48088e8e17a8b6f83e94036";
    name = "f9d6fe4a6ad9ed89dfc315f284124d2104377940.zip";
  }
  {
    url = "https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz";
    sha256 = "0b0e3aa07c8c063ddf40b082bdf7e37a1562bda40a0ff5272957f3e987e0e54b";
    name = "lz4-1.9.4.tar.gz";
  }
  {
    url = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz";
    sha256 = "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23";
    name = "zlib-1.3.1.tar.gz";
  }
  {
    url = "https://github.com/martinus/unordered_dense/archive/f30ed41b58af8c79788e8581fe57a6faf856258e.tar.gz";
    sha256 = "8393d08b2a41949c70345926515036df55643e80118b608bcec6f4202d4a3026";
    name = "f30ed41b58af8c79788e8581fe57a6faf856258e.tar.gz";
  }
  {
    url = "https://github.com/nelhage/rules_boost/archive/f5b0f8c904f2487d8f5a9a956d4388724e627210.tar.gz";
    sha256 = "c10b313b1661d6d96e73a0178fe9dcb188414a5d37b82fa13e106b53a264ba92";
    name = "f5b0f8c904f2487d8f5a9a956d4388724e627210.tar.gz";
  }
  {
    url = "https://github.com/nlohmann/json/releases/download/v3.11.3/include.zip";
    sha256 = "a22461d13119ac5c78f205d3df1db13403e58ce1bb1794edc9313677313f4a9d";
    name = "include.zip";
  }
  {
    url = "https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/1.9.6.tar.gz";
    sha256 = "f93b6dd7ce796b13d02c108bc9f79812245a82e577581c4c9aabe57075c90ea2";
    name = "1.9.6.tar.gz";
  }
  {
    url = "https://github.com/pinterest/ktlint/releases/download/1.3.0/ktlint";
    sha256 = "01b2e0ef893383a50dbeb13970fe7fa3be36ca3e83259e01649945b09d736985";
    name = "ktlint";
  }
  {
    url = "https://github.com/prometheus/prometheus/releases/download/v3.7.1/prometheus-3.7.1.linux-amd64.tar.gz";
    sha256 = "a2e8a89c09b14b2277e6151e87fc8ed18858486cbf89372656d71fcd666b51da";
    name = "prometheus-3.7.1.linux-amd64.tar.gz";
  }
  {
    url = "https://github.com/prometheus/prometheus/releases/download/v3.7.1/prometheus-3.7.1.linux-arm64.tar.gz";
    sha256 = "7ede3f3f0541b9bfd2ccca9cef57af80554f131b8e7af8900896c6e49ed2d4ef";
    name = "prometheus-3.7.1.linux-arm64.tar.gz";
  }
  {
    url = "https://github.com/protocolbuffers/protobuf/releases/download/v33.5/protobuf-33.5.bazel.tar.gz";
    sha256 = "692ea6352402599c72020d2487c8bace5c50439bac2029ed864b323e5e214e8b";
    name = "protobuf-33.5.bazel.tar.gz";
  }
  {
    url = "https://github.com/pybind/pybind11_bazel/releases/download/v2.12.0/pybind11_bazel-2.12.0.zip";
    sha256 = "a58c25c5fe063a70057fa20cb8e15f3bda19b1030305bcb533af1e45f36a4a55";
    name = "pybind11_bazel-2.12.0.zip";
  }
  {
    url = "https://github.com/redpanda-data/avro/archive/6821e2b454401308d4e3819c0569d0fe7f2a66fa.tar.gz";
    sha256 = "1c09dd94cc8fcac0fa99359254507cfd538c527bcb8b5066d16b6289ac87ea93";
    name = "6821e2b454401308d4e3819c0569d0fe7f2a66fa.tar.gz";
  }
  {
    url = "https://github.com/redpanda-data/rapidjson/archive/a47f8d7379e9d1dfbac415e7d8ccece605275e5b.tar.gz";
    sha256 = "bb6805bfb8d5491b7ba77019dda08ddb0912b853399409bbf8a74d8357581c9c";
    name = "a47f8d7379e9d1dfbac415e7d8ccece605275e5b.tar.gz";
  }
  {
    url = "https://github.com/redpanda-data/seastar/archive/a6ac2ff6190a4a9dce5059991355703e1073d11f.tar.gz";
    sha256 = "5918f72ec59c159a8d2fe36870e7d30c6e61426fde766d7dd6853fa7f9871f7f";
    name = "a6ac2ff6190a4a9dce5059991355703e1073d11f.tar.gz";
  }
  {
    url = "https://github.com/stonier/yaml-cpp/releases/download/0.8.0/yaml-cpp-0.8.0.tar.gz";
    sha256 = "fbe74bbdcee21d656715688706da3c8becfd946d92cd44705cc6098bb23b3a16";
    name = "yaml-cpp-0.8.0.tar.gz";
  }
  {
    url = "https://github.com/tukaani-project/xz/releases/download/v5.4.5/xz-5.4.5.tar.gz";
    sha256 = "135c90b934aee8fbc0d467de87a05cb70d627da36abe518c357a873709e5b7d6";
    name = "xz-5.4.5.tar.gz";
  }
  {
    url = "https://mirror.bazel.build/sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz";
    sha256 = "ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269";
    name = "bzip2-1.0.8.tar.gz";
  }
  {
    url = "https://services.gradle.org/distributions/gradle-8.5-bin.zip";
    sha256 = "9d926787066a081739e8200858338b4a69e837c3a821a33aca9db09dd4a41026";
    name = "gradle-8.5-bin.zip";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/omb/omb_minimal_3c624daad47f16ae7036b67142c384d3e59150bf.tar.gz";
    sha256 = "9d1f651d98a624dcfb09c213a8b77732bd08e037d32922b06c06e6027841e8ee";
    name = "omb_minimal_3c624daad47f16ae7036b67142c384d3e59150bf.tar.gz";
  }
  # Manually added after dev merge — gen-bazel-deps.py didn't pick these up:
  # supply-chain v0.0.5 is pinned by @package_metadata internally (MVS chose
  # v0.0.6 at the root but package_metadata still loads its own v0.0.5).
  {
    url = "https://github.com/bazel-contrib/supply-chain/releases/download/v0.0.5/supply-chain-v0.0.5.tar.gz";
    sha256 = "49ed11e5d6b752c55fa539cbb10b2736974f347b081d7bd500a80dacb7dbec06";
    name = "supply-chain-v0.0.5.tar.gz";
  }
  # Rust host toolchain — fetched by rules_rust at runtime, not declared in
  # MODULE.bazel. Version (1.95.0) tracks what rules_rust 0.70.0 requests.
  # rules_rust pulls rustc + cargo + rust-std + llvm-tools + clippy together.
  {
    url = "https://static.rust-lang.org/dist/rustc-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
    sha256 = "8426a3d170a5879f5682f5fbdd024a1779b3951e7baba685af2d6dc32a6dfc15";
    name = "rustc-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
  }
  {
    url = "https://static.rust-lang.org/dist/cargo-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
    sha256 = "e74edd2cf7d0f1f1383b4f00eb90c843750bc489e2ccf7214e6476678a907425";
    name = "cargo-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
  }
  {
    url = "https://static.rust-lang.org/dist/rust-std-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
    sha256 = "047ea7098803d3500fa1072e9cee5392697e21525559e4458128a2bf874aa382";
    name = "rust-std-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
  }
  {
    url = "https://static.rust-lang.org/dist/llvm-tools-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
    sha256 = "037d534bb21bf1d833bb9ef6e2304878ecc5cc04176b6674a90a73fa7a4ac0b1";
    name = "llvm-tools-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
  }
  {
    url = "https://static.rust-lang.org/dist/clippy-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
    sha256 = "ac779bc9839dd47180806b133e4e2563c4a34716284cd5b8fede8ef289f452ca";
    name = "clippy-1.95.0-x86_64-unknown-linux-gnu.tar.xz";
  }
  # rustfmt is pinned to a nightly snapshot (dated 2026-04-16) — rules_rust
  # 0.70.0 doesn't ship a stable rustfmt for the toolchain version it picks.
  {
    url = "https://static.rust-lang.org/dist/2026-04-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz";
    sha256 = "87c99089a8111888532865857dbcc1ebcf72668010ed042e3971736fd1a1340b";
    name = "rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz";
  }
  # Hermetic Python (python-build-standalone) — pulled by rules_python 1.7.0
  # for the default python.toolchain(python_version = "3.12") declaration.
  # We previously relied on a local rules_python fork's local_toolchain
  # mechanism (system Python from nixpkgs); upstream 1.7.0 doesn't expose
  # that, so we use the hermetic archive instead.
  {
    url = "https://github.com/astral-sh/python-build-standalone/releases/download/20251014/cpython-3.12.12+20251014-x86_64-unknown-linux-gnu-install_only.tar.gz";
    sha256 = "1ab2b6594d1c3d76cbebea09d6bc3e6ba68d8eb3b6322080375c4cc3dd188f34";
    name = "cpython-3.12.12+20251014-x86_64-unknown-linux-gnu-install_only.tar.gz";
  }
]
