{
  lib,
  stdenv,
  callPackage,
  runCommand,
  writeShellApplication,
  bazel_8,
  bazelisk,
  llvmPackages_20,
  python312,
  go,
  jdk_headless,
  autoconf,
  automake,
  libtool,
  bison,
  pkg-config,
  elfutils,
  xfsprogs,
  valgrind,
  patchelf,
  file,
  findutils,
  git,
  cacert,
  zstd,
  coreutils,
  bash,
  gnused,
  glibc,
  gcc-unwrapped,
  zlib,
  openssl,
  curl,
  lndir,
}:

let
  version = "0.0.0-dev";

  gccLib = stdenv.cc.cc.lib;

  # Local source with filter to exclude build artifacts
  localSrc = lib.cleanSourceWith {
    src = ./..;
    filter = path: type:
      !(builtins.elem (baseNameOf path) [
        ".git" "bazel-bin" "bazel-out" "bazel-redpanda"
        "bazel-testlogs" "result" "result-rpk"
      ]);
  };

  # Fetch the patched rules_python (nix-local-toolchain branch) and
  # embed it in the source tree so local_path_override works in the sandbox.
  rulesPythonSrc = builtins.fetchGit {
    url = "/home/das/Downloads/rules_python";
    ref = "nix-local-toolchain";
    rev = "b65ba9d68a489456fa45a924a1726c86fec08e88";
  };

  src = runCommand "redpanda-src-patched" { } ''
    cp -r --no-preserve=mode ${localSrc} $out

    # Embed rules_python in tree
    mkdir -p $out/third_party
    cp -r --no-preserve=mode ${rulesPythonSrc} $out/third_party/rules_python

    # Rewrite local_path_override to in-tree copy
    sed -i 's|path = "/home/das/Downloads/rules_python"|path = "third_party/rules_python"|' $out/MODULE.bazel

    # Add exec_os to skip /etc/os-release detection in the Nix sandbox
    sed -i 's/llvm.toolchain(/llvm.toolchain(\n            exec_os = "linux",/' $out/MODULE.bazel

    # Patch rules_buf to not download buf binaries (transitive dep, not used
    # by Redpanda). Without this, the buf repo rule downloads sha256.txt at
    # fetch time without a content hash, which can't be served from the repo
    # cache and fails in the sandbox.
    cat >> $out/MODULE.bazel <<'BUFPATCH'

# Nix: stub out buf toolchain downloads (not needed for the build)
single_version_override(
    module_name = "rules_buf",
    patch_strip = 1,
    patches = ["//bazel/thirdparty:rules_buf-nix-no-download.patch"],
)
BUFPATCH

    # Use host Go SDK instead of downloading from go.dev.
    # go_sdk.download() first fetches a JSON version list from go.dev which
    # can't be served from the repo cache (no content hash). go_sdk.host()
    # uses Go from PATH (provided by nativeBuildInputs) instead.
    sed -i '/^go_sdk = use_extension/,/^$/c\
go_sdk = use_extension("@rules_go\/\/go:extensions.bzl", "go_sdk", dev_dependency = True)\
go_sdk.host()\
' $out/MODULE.bazel
    # Remove the go_sdk_with_systemcrypto block (not needed for Nix build)
    sed -i '/^# The microsoft compiler versions/,/^)$/d' $out/MODULE.bazel

    # Fix rules_cc shebangs: #!/bin/bash → #!/bin/sh
    # /bin/bash doesn't exist in the Nix sandbox; /bin/sh does (it's bash).
    # Uses patch_cmds so Bazel applies these during extraction, persisting
    # even when Bazel re-validates/re-extracts repos.
    cat >> $out/MODULE.bazel <<'CCPATCH'

# Nix: fix shebangs in rules_cc toolchain scripts
# Handles both #!/bin/bash and #!/usr/bin/env bash variants.
single_version_override(
    module_name = "rules_cc",
    patch_cmds = [
        "sed -i '1s|#!/usr/bin/env bash|#!/bin/sh|; 1s|#!/bin/bash|#!/bin/sh|' cc/private/toolchain/generate_system_module_map.sh cc/private/toolchain/grep-includes.sh cc/private/toolchain/link_dynamic_library.sh",
    ],
)
CCPATCH

    # Export the patch file so Bazel can resolve the label
    echo 'exports_files(["rules_buf-nix-no-download.patch"])' >> $out/bazel/thirdparty/BUILD

    # Replace default BCR registry with local copy (the --registry flag is
    # a list flag — CLI values append rather than replace, so we must patch
    # the .bazelrc source to remove the remote URL)
    sed -i 's|common --registry=https://bcr.bazel.build|common --registry=file://${registry}|' $out/.bazelrc

    # Use pre-generated lockfile that matches the patched MODULE.bazel.
    # Generated by running: bazelisk mod deps --lockfile_mode=update
    # with the same MODULE.bazel patches applied locally.
    # This prevents lockfile staleness from triggering module re-resolution
    # (which would need network access unavailable in the sandbox).
    cp ${./MODULE.bazel.lock.nix} $out/MODULE.bazel.lock
  '';

  registry = callPackage ./bcr.nix { };

  bazel = bazel_8;  # actual binary, used via USE_BAZEL_VERSION
  # Platform-specific wrapper (avoids the generic `bazel` wrapper which
  # re-reads USE_BAZEL_VERSION and double-resolves).
  bazelPlatformBin = let
    os = if stdenv.isLinux then "linux" else "darwin";
    arch = stdenv.hostPlatform.uname.processor;
  in "${bazel}/bin/bazel-8.5.0-${os}-${arch}";
  targets = [ "//src/v/redpanda:redpanda" ];

  # ── Nixify pipeline configuration ──
  # Imported from nixify-rules.nix — centralizes all fixup config.
  nixifyRules = import ./nixify-rules.nix {
    inherit lib bash glibc gcc-unwrapped zlib openssl curl;
  };

  # Extract patchelf and shebang config from nixify rules
  patchelfRule = lib.findFirst (r: r.type == "patchelf") null nixifyRules;
  nixInterp = patchelfRule.interpreter;
  nixRpath = patchelfRule.rpath;

  shebangsRule = lib.findFirst (r: r.type == "fix-shebangs") null nixifyRules;

  # ── Per-archive repo cache (linkFarm) ──
  # Each archive is fetched independently via fetchurl, then assembled
  # into a content_addressable/sha256/<hex>/file layout that Bazel
  # recognizes as a repository cache. Adding/removing an archive only
  # rebuilds that single fetchurl — no monolithic FOD hash to manage.
  repoCache = callPackage ./bazel-repo-cache.nix { } {
    archives = import ./bazel-deps.nix;
  };

  nativeBuildInputsDeps = [
    bazelisk
    llvmPackages_20.libcxxClang
    llvmPackages_20.lld
    llvmPackages_20.llvm
    llvmPackages_20.libcxx
    python312
    go
    jdk_headless
    autoconf
    automake
    libtool
    bison
    pkg-config
    elfutils
    xfsprogs
    valgrind
    patchelf
    file
    findutils
    git
    cacert
    zstd
    coreutils
    bash
    gnused
  ];

  nixPath = lib.makeBinPath (nativeBuildInputsDeps ++ [ bazel stdenv.cc stdenv.cc.bintools ]);

  # shellcheck-validated script for patching Bazel-downloaded binaries.
  # Fixes two problems in the Nix sandbox:
  #   1. ELF binaries have /lib64/ld-linux-x86-64.so.2 interpreter (doesn't exist)
  #   2. Shell scripts have #!/bin/bash shebang (doesn't exist)
  bazelPatcher = writeShellApplication {
    name = "bazel-sandbox-patcher";
    runtimeInputs = [ patchelf file findutils coreutils gnused ];
    text = ''
      NIX_INTERP="${nixInterp}"
      NIX_RPATH="${nixRpath}"
      NIX_BASH="${shebangsRule.to}"

      patch_one_elf() {
        local f="$1"
        local desc
        desc=$(file -b "$f" 2>/dev/null) || return 0
        case "$desc" in
          ELF*dynamically\ linked*) ;;
          *) return 0 ;;
        esac
        local interp
        interp=$(patchelf --print-interpreter "$f" 2>/dev/null) || return 0
        case "$interp" in
          /nix/store/*) return 0 ;;
        esac
        echo "  patchelf: $f (was: $interp)"
        chmod u+w "$f" 2>/dev/null || true
        patchelf --set-interpreter "$NIX_INTERP" "$f" 2>/dev/null || true
        local old_rpath
        old_rpath=$(patchelf --print-rpath "$f" 2>/dev/null) || old_rpath=""
        patchelf --set-rpath "$NIX_RPATH:$old_rpath" "$f" 2>/dev/null || true
      }

      patch_elfs() {
        local dir="$1"
        echo "Scanning $dir for ELF binaries to patch..."
        while IFS= read -r -d "" f; do
          patch_one_elf "$f"
        done < <(find -L "$dir" -type f \
          \( -executable -o -name "*.so" -o -name "*.so.*" \) \
          -print0 2>/dev/null)
      }

      fix_bash_shebangs() {
        local dir="$1"
        echo "Fixing bash shebangs in $dir..."
        while IFS= read -r -d "" f; do
          local first
          first=$(head -c 19 "$f" 2>/dev/null) || continue
          case "$first" in
            '#!/usr/bin/env bash'*)
              chmod u+w "$f" 2>/dev/null || true
              sed -i "1s|#!/usr/bin/env bash|#!$NIX_BASH|" "$f"
              echo "  fixed shebang: $f"
              ;;
            '#!${shebangsRule.from}'*)
              chmod u+w "$f" 2>/dev/null || true
              sed -i "1s|#!${shebangsRule.from}|#!$NIX_BASH|" "$f"
              echo "  fixed shebang: $f"
              ;;
          esac
        done < <(find "$dir" -type f \
          \( -name "*.sh" -o -executable \) \
          -print0 2>/dev/null)
      }

      command="''${1:-}"
      shift || true

      case "$command" in
        patch-all)
          for dir in "$@"; do
            if [ -d "$dir" ]; then
              patch_elfs "$dir"
              fix_bash_shebangs "$dir"
            fi
          done
          ;;
        patch-elfs)
          for dir in "$@"; do
            [ -d "$dir" ] && patch_elfs "$dir"
          done
          ;;
        fix-shebangs)
          for dir in "$@"; do
            [ -d "$dir" ] && fix_bash_shebangs "$dir"
          done
          ;;
        *)
          echo "Usage: bazel-sandbox-patcher {patch-all|patch-elfs|fix-shebangs} DIR..."
          exit 1
          ;;
      esac
    '';
  };

  # Generate .bazelrc.nix content (same settings as shell.nix shellHook)
  bazelrcNix = ''
    build --config=system-clang
    build --shell_executable=${bash}/bin/bash
    build --action_env=PATH=${nixPath}
    build --host_action_env=PATH=${nixPath}
    build --action_env=NIX_LDFLAGS
    build --host_action_env=NIX_LDFLAGS
    build --action_env=NIX_CFLAGS_COMPILE
    build --host_action_env=NIX_CFLAGS_COMPILE
    build --action_env=NIX_CC
    build --host_action_env=NIX_CC
    build --action_env=NIX_BINTOOLS
    build --host_action_env=NIX_BINTOOLS
    build --action_env=NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu
    build --host_action_env=NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu
    build --action_env=NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu
    build --host_action_env=NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu
    build --action_env=NIX_HARDENING_ENABLE
    build --host_action_env=NIX_HARDENING_ENABLE
    build --action_env=NIX_ENFORCE_NO_NATIVE
    build --host_action_env=NIX_ENFORCE_NO_NATIVE
    build --action_env=ACLOCAL_PATH=${lib.concatStringsSep ":" [
      "${automake}/share/aclocal"
      "${libtool}/share/aclocal"
      "${pkg-config}/share/aclocal"
    ]}
    build --host_action_env=ACLOCAL_PATH=${lib.concatStringsSep ":" [
      "${automake}/share/aclocal"
      "${libtool}/share/aclocal"
      "${pkg-config}/share/aclocal"
    ]}
    build --action_env=LIBRARY_PATH=${llvmPackages_20.libcxx}/lib:${gccLib}/lib
    build --host_action_env=LIBRARY_PATH=${llvmPackages_20.libcxx}/lib:${gccLib}/lib
    build --action_env=LD_LIBRARY_PATH=${llvmPackages_20.libcxx}/lib:${gccLib}/lib
    build --host_action_env=LD_LIBRARY_PATH=${llvmPackages_20.libcxx}/lib:${gccLib}/lib
    build --linkopt=-Wl,-rpath,${llvmPackages_20.libcxx}/lib
    build --linkopt=-Wl,-rpath,${gccLib}/lib
    build --host_linkopt=-Wl,-rpath,${llvmPackages_20.libcxx}/lib
    build --host_linkopt=-Wl,-rpath,${gccLib}/lib
    build --@protobuf//bazel/toolchains:allow_nonstandard_protoc
  '';

  commonArgs = [
    "--repository_cache=repo_cache"
    "--shell_executable=${bash}/bin/bash"
    "--action_env=PATH=${nixPath}"
    "--repo_env=PATH=${nixPath}"
    "--repo_env=BAZEL_SH=${bash}/bin/bash"
    "--action_env=BAZEL_SH=${bash}/bin/bash"
    "--repo_env=SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt"
    "--action_env=SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt"
    "--spawn_strategy=local"
  ];

  # Patch all Bazel external dirs in the output base
  patchBazelDirs = ''
    ${bazelPatcher}/bin/bazel-sandbox-patcher patch-all \
      "$HOME"/.cache/bazel/_bazel_*/*/external \
      "$HOME"/.cache/bazel/_bazel_*/*/modextwd
  '';

in
stdenv.mkDerivation {
  name = "redpanda-${version}";
  inherit src version;
  sourceRoot = "redpanda-src-patched";

  nativeBuildInputs = nativeBuildInputsDeps ++ [ bazel bazelPatcher lndir ];

  requiredSystemFeatures = [ "big-parallel" ];

  passthru = {
    inherit repoCache;
  };

  buildPhase = ''
    runHook preBuild

    export HOME=$(mktemp -d)

    # Write .bazelrc.nix
    cat > .bazelrc.nix <<'BAZELRC'
    ${bazelrcNix}
    BAZELRC

    export CC=clang
    export CXX=clang++

    # Point bazelisk at the nixpkgs bazel_8 platform wrapper (no runtime
    # download). Must NOT point to the generic `bazel` wrapper — it re-reads
    # USE_BAZEL_VERSION and double-resolves.
    export USE_BAZEL_VERSION=${bazelPlatformBin}

    # Bazel needs to find bash for patch_cmds, repo rule shell commands, etc.
    # --repo_env only makes it available to repository_ctx.os.environ, but
    # patch_cmds (module resolution phase) reads the process environment.
    export BAZEL_SH=${bash}/bin/bash

    # Disable canonical ID so Bazel uses pure content-addressing
    export BAZEL_HTTP_RULES_URLS_AS_DEFAULT_CANONICAL_ID=0

    # Create a writable copy of the repo cache. The linkFarm is in the
    # read-only Nix store, but Bazel needs to write to the cache dir
    # (e.g. caching registry file lookups). lndir creates a writable
    # directory tree with symlinks to the actual archive files.
    mkdir -p repo_cache
    ${lndir}/bin/lndir -silent ${repoCache} repo_cache

    # ── Phase A: Initial fetch ──
    # Extracts archives from the pre-populated repo cache.
    # Will fail because downloaded ELF binaries (Rust, Go, etc.)
    # can't execute in the Nix sandbox without patching.
    echo "=== Fetch attempt 1 ==="
    bazelisk \
      fetch \
      --keep_going \
      ${lib.escapeShellArgs commonArgs} \
      ${lib.escapeShellArgs targets} || true

    # Diagnostics: check if patch_cmds worked on rules_cc
    echo "=== Diagnostics: rules_cc shebang check ==="
    for f in "$HOME"/.cache/bazel/_bazel_*/*/external/rules_cc+/cc/private/toolchain/generate_system_module_map.sh; do
      if [ -f "$f" ]; then
        echo "  Found: $f"
        echo "  Shebang: $(head -1 "$f")"
      else
        echo "  NOT FOUND: $f"
      fi
    done
    echo "  BAZEL_SH=$BAZEL_SH"
    echo "  /bin/sh exists: $(test -x /bin/sh && echo YES || echo NO)"
    echo "  bash on PATH: $(which bash 2>/dev/null || echo NOT FOUND)"

    # ── Phase B+C: Nixify + re-fetch loop ──
    # Patch extracted binaries, then re-fetch. Multiple rounds because
    # Bazel may re-extract archives (losing patches) when repo rules
    # re-run with now-working binaries.
    for attempt in 2 3 4; do
      echo "=== Nixify pass (before attempt $attempt) ==="
      ${patchBazelDirs}

      echo "=== Fetch attempt $attempt ==="
      if bazelisk \
        fetch \
        --keep_going \
        ${lib.escapeShellArgs commonArgs} \
        ${lib.escapeShellArgs targets}; then
        echo "=== Fetch succeeded on attempt $attempt ==="
        break
      fi
    done

    # Final nixify pass before build
    echo "=== Final nixify pass ==="
    ${patchBazelDirs}

    # ── Phase D: Build ──
    bazelisk \
      build \
      ${lib.escapeShellArgs commonArgs} \
      ${lib.escapeShellArgs targets}

    # Shut down the persistent server
    bazelisk shutdown || true

    runHook postBuild
  '';

  installPhase = ''
    mkdir -p $out/bin $out/etc/redpanda
    install -m755 bazel-bin/src/v/redpanda/redpanda $out/bin/redpanda
    install -m644 conf/redpanda.yaml $out/etc/redpanda/redpanda.yaml
  '';

  meta = {
    description = "Redpanda: a Kafka-compatible streaming data platform";
    homepage = "https://redpanda.com/";
    license = lib.licenses.bsl11;
    platforms = [ "x86_64-linux" "aarch64-linux" ];
    mainProgram = "redpanda";
  };
}
