# wasmtime-c-api.nix — wasmtime C API built from source, exact-version-pinned.
#
# Replicates the nixpkgs `wasmtime` package (sourced from commit
# e1d08c1580a3, which packaged 42.0.1) with two modifications:
#   1. Bumped to 42.0.2 to match upstream MODULE.bazel / Cargo.lock.
#   2. enableStatic = true so libwasmtime.a is preserved (the rust
#      crate_universe build that this derivation substitutes also
#      produces a static lib; redpanda's wasmtime.cc links it as
#      a cc_import static_library).
#
# Outputs:
#   out  — wasmtime CLI binary (we don't use it, but keeps the build
#          machinery simple)
#   dev  — include/wasm.h, include/wasmtime/*.h{,h}, etc. (with conf.h
#          generated by build.rs; see postInstall)
#   lib  — lib/libwasmtime.{a,so}
{
  lib,
  stdenv,
  rustPlatform,
  fetchFromGitHub,
  cmake,
  installShellFiles,
  versionCheckHook,
  enableShared ? !stdenv.hostPlatform.isStatic,
  enableStatic ? true,
}:
rustPlatform.buildRustPackage (finalAttrs: {
  pname = "wasmtime-c-api";
  version = "42.0.2";

  src = fetchFromGitHub {
    owner = "bytecodealliance";
    repo = "wasmtime";
    tag = "v${finalAttrs.version}";
    hash = "sha256-LfWnYZz5cmEP6eI92HCK7ATRE901L5c7sfIxn5VyHUc=";
    fetchSubmodules = true;
  };

  auditable = false;

  cargoHash = "sha256-b2zZVqQbPrtcbSk1oTiJqhwE1OczTTiLpRLNPFBpSE8=";

  cargoBuildFlags = [
    "--package"
    "wasmtime-cli"
    "--package"
    "wasmtime-c-api"
  ];

  outputs = [
    "out"
    "dev"
    "lib"
  ];

  nativeBuildInputs = [
    cmake
    installShellFiles
  ];

  # Skip wasmtime's own test suite (SIMD-platform-gated; not relevant for our
  # downstream linkage).
  doCheck = false;

  postInstall =
    let
      inherit (stdenv.hostPlatform.rust) cargoShortTarget;
    in
    ''
      moveToOutput lib $lib
      ${lib.optionalString (!enableShared) "rm -f $lib/lib/*.so{,.*}"}
      ${lib.optionalString (!enableStatic) "rm -f $lib/lib/*.a"}

      # The C API headers are generated by build.rs at compile time, not
      # checked into the source tree. Copy them from the cargo build dir.
      # https://github.com/rust-lang/cargo/issues/9661
      mkdir $dev
      cp -r target/${cargoShortTarget}/release/build/wasmtime-c-api-impl-*/out/include $dev/include
    '';

  # Skip install check — versionCheckHook looks for a binary matching
  # pname ("wasmtime-c-api"), but the actual CLI binary is named
  # "wasmtime". We don't ship the CLI from this derivation; consumers
  # use ${lib}/lib/libwasmtime.{a,so} + ${dev}/include only.
  doInstallCheck = false;

  meta = {
    description = "Wasmtime C API (built from source, pinned to v42.0.2)";
    homepage = "https://wasmtime.dev/";
    license = lib.licenses.asl20;
    platforms = lib.platforms.unix;
    mainProgram = "wasmtime";
  };
})
